// ==================== src/enums/EffectType.js ====================
const EffectType = {
  STRENGTH_MOD: 'STRENGTH_MOD',
  AGILITY_MOD: 'AGILITY_MOD',
  CONSTITUTION_MOD: 'CONSTITUTION_MOD',
  SKILL_MOD: 'SKILL_MOD',
  DOT_HP: 'DOT_HP',
  ACTION_SPEED_MOD: 'ACTION_SPEED_MOD',
  ARMOR_COVERAGE_MOD: 'ARMOR_COVERAGE_MOD',
  ARMOR_DEFENSE_MOD: 'ARMOR_DEFENSE_MOD',
  DAMAGE_MOD: 'DAMAGE_MOD',
  PENETRATION_MOD: 'PENETRATION_MOD',
  MOVE_DISTANCE_MOD: 'MOVE_DISTANCE_MOD',
  STUN: 'STUN',
  SILENCE: 'SILENCE',
  BLIND: 'BLIND'
};

export default EffectType;